# fly.toml app configuration file generated for flashacom on 2023-05-24T12:53:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flashacom"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
